version: "3.4"

services:

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    env_file: ./env/db.env
    restart: always
    command: supervisord -n

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
